### ISSUE TITLE
Align top doesn't work in LC

### ISSUE THREAD

**Issue by MrKuip** [mikaelgrev/miglayout#108]
The align top doesn't work if it is set in the LC (LayoutConstraint).
The following code doesn't align button1 to the top:

```
package org.kku.jdiskusage.main;

import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import net.miginfocom.swing.MigLayout;

public class TestSwing
{
  public TestSwing()
  {
  }

  public void start()
  {
    JPanel pane;
    MigLayout layout;
    JFrame frame;
    JButton button1;
    JButton button2;

    layout = new MigLayout("debug, top", "[][]", "[]");
    pane = new JPanel();
    pane.setLayout(layout);

    button1 = new JButton("Button 1");
    button1.setFont(new Font("Arial", Font.PLAIN, 10));
    button2 = new JButton("Button 2");
    button2.setFont(new Font("Arial", Font.PLAIN, 20));

    pane.add(button1);
    pane.add(button2);

    frame = new JFrame("Test");
    frame.setContentPane(pane);
    frame.setSize(new Dimension(600, 400));
    frame.setVisible(true);
  }

  public static void main(String[] args)
  {
    new TestSwing().start();
  }
}
```
![image](https://github.com/mikaelgrev/miglayout/assets/15797225/e3aacc2c-3e42-4442-bb58-feeb95e12c4e)

Setting align top in the RC (RowConstraints) aligns button1 correctly to the top.
This works:
`    layout = new MigLayout("debug", "[][]", "[top]");`

![image](https://github.com/mikaelgrev/miglayout/assets/15797225/d06eca96-28cf-44e5-9560-520743db0ea2)

**Comment by DevCharly** [comment]
> The align top doesn't work if it is set in the LC (LayoutConstraint).

It works, but your expectations are wrong 😉 

Alignment in LC specifies alignment of whole grid in container, and not of components in cell as you expect.
See https://www.formdev.com/jformdesigner/doc/layouts/miglayout-whitepaper/#layout_cons_align

Try `layout = new MigLayout("debug, right", "[][]", "[]");` and it looks like this:

![grafik](https://github.com/mikaelgrev/miglayout/assets/5604048/49e56a8f-be04-4e8d-96d1-e6f3e65339cf)

**Comment by MrKuip** [comment]
Thanks for the clarification. 
I will close this issue
