### ISSUE TITLE
absolute layout (x,y,w,h) looks different on Windows and Mac (windows wrong)

### ISSUE THREAD

**Issue by tobium** [mikaelgrev/miglayout#31]
in MigLayout 5.1 (current snapshot) there are layout problems on Windows and Mac. The main problem ist: When I make a layout via absolute coordinates (x,y,w,h), the layout on Windows is rendered wrong, on Mac it's correct.

![miglayout-mac](https://cloud.githubusercontent.com/assets/2484805/8124549/0235acb0-10dd-11e5-893a-59d117694b9a.png)
![miglayout-win](https://cloud.githubusercontent.com/assets/2484805/8124550/025f033a-10dd-11e5-8ba6-7b0243f62757.png)

# Example:
Example shows a Label which should have 50% of width of the parent container (frame). On Mac it's correct, on windows width is higher than 50%... 

```java
package com.ultramixer;

import net.miginfocom.swing.MigLayout;
import javax.swing.*;

public class TestMigLayout extends JFrame
{
    public TestMigLayout()
    {
        this.setLayout(new MigLayout("hidemode 2,debug,ins 0", "[]", "[]"));

        JLabel label = new JLabel("TEST MIGLAYOUT");
        this.add(label, "x 0, y 0, w 250, h 200");

        this.setSize(500, 400);
        this.setVisible(true);
    }

    public static void main(String[] args)
    {
        new TestMigLayout();
    }
}
```

**Comment by JFormDesigner** [comment]
This is because MigLayout uses **logical pixels** by default, which depend on screen DPI. Looking at the large Windows border in your screen shot, it seems that is uses larger DPI than your Mac.

If you want use real pixels, try
```java
this.add(label, "x 0, y 0, w 250px, h 200px");
```
Or change the default unit to real pixels:
```java
PlatformDefaults.setDefaultHorizontalUnit(UnitValue.PIXEL);
PlatformDefaults.setDefaultVerticalUnit(UnitValue.PIXEL);
```

You could also indicate that the size of a logical pixel should always be a real pixel with:
```java
PlatformDefaults.setLogicalPixelBase( PlatformDefaults.BASE_REAL_PIXEL );
```

**Comment by JFormDesigner** [comment]
BTW would be interesting to know what Java version you use and the resolution of your screen.
Also a screenshot comparing a Java button with a native Windows button (to see any difference in size).

**Comment by tobium** [comment]
Thank you JFormDesigner :) After debugging through the code I found this PIXEL vs. LPX difference ;)

So after setting the default unit, everything works fine - in the same manner like MigLayout 4.

But is it a good idea to switch the default unit between ML4 and 5 from PX to LPX? It could be confusing for many people like me ;)

Thank you for your help. MigLayout is the best layout manager available. So I hope one day MigLayout is as popular as the built-in layout manager - or even better - will be integrated in the offiical JDK...

Best,
Tobi

**Comment by tbee** [comment]
Integrated into the JDK... Hm, it is a recognition, but it would stifle any development.
