### ISSUE TITLE
Component grows unexpectedly in height

### ISSUE THREAD

**Issue by essentinal** [mikaelgrev/miglayout#41]
Since I upgraded to MigLayout 5.0, I got an issue with my JLabel displaying HTML text. First I thought the HTML rendering is broken but then I realized it works with MigLayout 4.2. Note: it does not happen when I remove the `<li>` tags.

Here is an example:

```
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

import net.miginfocom.swing.MigLayout;

public class TestLITag {
  public static void main(final String[] args) {

    SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {

        final String s = "<html><p>Connection refused, the server does not respond as expected</p>"
            + "<li>Check the URL below, especially the port</li>"
            + "<li>Check the connection to the device</li>"
            + "<li>Check the port configuration of the device</li>"
            + "<li>Check the configuration of your antivirus or firewall software</li>"
            + "<li>Contact your administrator</li>"
            + "<li>Contact our service or send an error report</li>"
            + "</html>";

        final JLabel warningLabel = new JLabel(s);

        final JPanel p = new JPanel(new MigLayout());

        p.add(warningLabel);

        JOptionPane.showMessageDialog(null, p);
      }
    });

  }
}
```

**Comment by mikaelgrev** [comment]
Hello,

I have seen this and put it in my work queue. Just a note, Swing doesn't have the notion (like JavaFX) to ask "what's the height given xx width.", so this might not be solvable. That it worked in 4.2 can be because of some re-layout thing that exposed other problems.

But, I will try to look at it more closely.

**Comment by Paul-Pech** [comment]
Hi,

I second this report. After updating from 4.3 to 5.1 the height of JLabels with html content seems to surprisingly large, compared to JLabels without html content, and independent of the use of li tags:

	public static void main(String [ ] args) {

		SwingUtilities.invokeLater(new Runnable() {			
			@Override
			public void run() {
				
				JFrame jf=new JFrame();
				JPanel pPlain=new JPanel(), pHtml=new JPanel(); 
				
				jf.getContentPane().setLayout(new MigLayout("debug","[]","[][]"));
				
				pPlain.setLayout(new MigLayout("debug", "[]", "[][]"));
				pHtml.setLayout(new MigLayout("debug", "[]", "[][]"));
				
				pPlain.add(new JLabel("plain line1"),"cell 0 0");
				pPlain.add(new JLabel("plain line2"),"cell 0 1");
				
				pHtml.add(new JLabel("<html>html line1</html>"),"cell 0 0");
				pHtml.add(new JLabel("<html>html line2</html>"),"cell 0 1");
											
				
				jf.getContentPane().add(pPlain,"cell 0 0");
				jf.getContentPane().add(pHtml,"cell 0 1");
				
				jf.pack();
				jf.setVisible(true);
				
			}
		});
	}

As a workaround, if it is known that a JLabel containing html content will fit into a single line, its height can be limited by using "hmax". Any other ideas?

Paul

![html_label](https://cloud.githubusercontent.com/assets/7048968/12719708/328a196e-c8f7-11e5-99b0-be0a29eefd03.png)

**Comment by Paul-Pech** [comment]
Hi,

I believe I found another possible workaround: Just add "growy" when you add the JLabel with Html content.

For essentinal's example this would be:

`p.add(warningLabel,"growy");`

and for my example this would be:

`pHtml.add(new JLabel("<html>html line1</html>"),"cell 0 0, growy");
pHtml.add(new JLabel("<html>html line2</html>"),"cell 0 1, growy");
`

Paul

**Comment by mikaelgrev** [comment]
Hello,

This has been noted and put in the work queue.

**Comment by mikaelgrev** [comment]
JenRue, can you post a minimal working example that shows the problem?

**Comment by JenRue** [comment]
Hello Mikael,
thank you for your reply and your time.

```
import java.awt.EventQueue;
import javax.swing.JFrame;
import javax.swing.JLabel;
import net.miginfocom.swing.MigLayout;

@SuppressWarnings("serial")
public class TestMigLayoutHtmlIssue extends JFrame {
    public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TestMigLayoutHtmlIssue().setVisible(true);
            }
        });
    }

    // - - -
    protected TestMigLayoutHtmlIssue() {
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        getContentPane().setLayout(new MigLayout());
        getContentPane().add(new JLabel("<html>'g r o w y': 0 1 2 3 4 5 6 7 8 9 0</html>"), "growy");
        getContentPane().add(new JLabel("<html>P R O B L E M : 0 1 2 3 4 5 6 7 8 9 0</html>"), "newline");
        getContentPane().add(new JLabel("<html>'a l i g n y c e n t e r': 0 1 2 3 4 5 6 7 8 9 0</html>"), "newline, aligny center");
        getContentPane().add(new JLabel("<html>g e t B a s e l i n e: 0 1 2 3 4 5 6 7 8 9 0</html>") {
            @Override
            public int getBaseline(int width, int height) {
                return -1; // simulate 'no BaseLine'
            }
        }, "newline");
        getContentPane().add(new JLabel("<html>g e t B a s e l i n e: 0 1 2 3 4 5 6 7 8 9 0</html>") {
            @Override
            public int getBaseline(int width, int height) {
                final int baseLine = super.getBaseline(width, height); // get the BaseLine in case of minimal width
                System.out.println(getPreferredSize());
                super.getBaseline(Integer.MAX_VALUE, 0);               // repair preferredSize
                System.out.println(getPreferredSize());
                return baseLine;
            }
        }, "newline");
        pack();
    }

    /* The reason for the enlargement is the call of the function
     *     SwingComponentWrapper.hasBaseline().
     * This function calls JComponent.getBaseline(int width, int height) with the minimal width.
     * This causes the calculation of the labels maximum height. Every space in the html- text is
     * replaced by a line feed.
     * So the preferred height is growing up by number of spaces respective the possible line feeds.
     *
     * What is the reason for calculate the BaseLine with the minimal dimensions?
     * Maybe an other solution is, to call "getBaseline(Integer.MAX_VALUE, 0);"
     */
}
```

**Comment by mikaelgrev** [comment]
Thanks for the good example. I have committed a fix along the lines you suggested.
Swing really should have a hasBaseLine() method and not just return an invalid value -1 like now.

**Comment by JenRue** [comment]
Sorry, but I'm confused - I can't see any change in the described behavior in the most recent git version.
Is it possible for you, to check the issue with my example?

**Comment by mikaelgrev** [comment]
I just tried your test and it works for me. If I set it back to use the minimum size it fails just like you described. Check that you have in git on row 333:

bl = getBaseline(8192, 8192) > -1;

**Comment by JenRue** [comment]
I'm not so firm with git, but if I check the URL
https://github.com/mikaelgrev/miglayout/blob/master/swing/src/main/java/net/miginfocom/swing/SwingComponentWrapper.java
then I only see the line 331 with
bl = getBaseline(d.width, d.height) > -1;

**Comment by mikaelgrev** [comment]
Oh, frack. IDEA has changed the dialog for commit so it doesn't pull down when you press the LEFT part of the button (even though the tooltips say so), it just commits and doesn't allow to push, so I forgot that.. Pushed now.

**Comment by JenRue** [comment]
thank you very much - now it works like expected - do you know, when there will be a new release of miglayout?

**Comment by mikaelgrev** [comment]
Probably not in a while since every time I have to struggle with Maven and Sonatype to get it all to work.

**Comment by swimmesberger** [comment]
Would appreciate a release with this fix

**Comment by tbee** [comment]
I'll try to create a release this week.

**Comment by tbee** [comment]
5.2 is out there

**Comment by JFormDesigner** [comment]
@tbee could you please add a git tag for the 5.2 release. Thx.

**Comment by tbee** [comment]
done
