### ISSUE TITLE
For JavaFX MigPane, calling "add" with an index has no effect

### ISSUE THREAD

**Issue by ebsmith1515** [mikaelgrev/miglayout#44]
After running the code below in my application. the labels were shown in the order "second", "first". The label with "first" should have been first. This was working, but then broke after the latest snapshot update.

```
//where menuContainer is already created in some fxml
Label label1 = new Label("first");
Label label2 = new Label("second");
menuContainer.add(label2);
menuContainer.add(0, label1);
```

**Comment by tbee** [comment]
Interesting. We did add retrolamba two days ago. I'll take a peek.

**Comment by tbee** [comment]
Ah. I can reproduce it. I've replaced a stream statement with something else so I could use retrolambda. That is the culprit.

**Comment by tbee** [comment]
Fixed it, new snapshot is in the repo.
