### ISSUE TITLE
Swing Demo's Grow Shrink Example has incorrect documentation

### ISSUE THREAD

**Issue by Tinhorn** [mikaelgrev/miglayout#63]
In the demo of Grow Shrink, there is this document 

> 'shp' means Shrink Priority. Lower values will be shrunk before higer ones and the default value is 100.

But it is the other way around, as shown by the demo itself and other [documentation](http://www.migcalendar.com/miglayout/mavensite/docs/cheatsheet.html)

**Comment by mikaelgrev** [comment]
Fixed. Thanks!
