### ISSUE TITLE
Is the documentation obsolete regarding default unit?

### ISSUE THREAD

**Issue by mgrojo** [mikaelgrev/miglayout#64]
The whitepaper says this:

> No unit specified. This is the default unit and pixels will be used by default. Default unit can be set with <code>PlatformDefaults.setDefaultUnit(int)</code>. E.g. <code>"10"</code></li>
>

But what can be seen in the source code in PlatformDefaults.java is:
```
	private static int DEF_H_UNIT = UnitValue.LPX;
	private static int DEF_V_UNIT = UnitValue.LPY;
```

Does that mean that the documentation is not up to date, or am I missing something?

**Comment by mikaelgrev** [comment]
The whitepaper is wrong, logical pixels are default.
