### ISSUE TITLE
JavaFX MigPane not updating after using getLayoutConstraints().setWrapAfter()

### ISSUE THREAD

**Issue by chaddaniels** [mikaelgrev/miglayout#66]
I'm using a MigPane in JavaFX, and updating the wrap value in the layout constraints dynamically using `getLayoutConstraints().setWrapAfter(newWrapValue)`.  The issue is that this doesn't seem to force a relayout of the pane.  I've tried following that up with a few things including `requestLayout()` and `setNeedsLayout(true)`, but the only thing I've found that seems to force a relayout is changing the children nodes of the pane.

As a side note, I had the same issue with row and column size constraints (ex. `getColumnConstraints().size()`), and calling `requestLayout()` after those changes did in fact force a relayout.

**Comment by mikaelgrev** [comment]
LayoutConstrints are just dead holder objects and no one knows if you change them. 

You can just re-set it with setLayoutConstraints(yourChangedLc) to make MigPane pick it up.

**Comment by chaddaniels** [comment]
Thank you.  Setting new constraints works as expected.
