### ISSUE TITLE
miglayout-core doesn't work on Android because of missing java.beans classes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mikaelgrev/miglayout#7]
```
...
```

Original issue reported on code.google.com by `software...@googlemail.com` on 2 Dec 2013 at 3:17

**Comment by JFormDesigner** [comment]
Because now using retrolambda (since 104b0c974f837cfcb22270d556399e338128a5c6), I think this issue can be closed...

See also https://twitter.com/tbeernot/status/701852168496799744
