### ISSUE TITLE
Is soft-wrap possible?

### ISSUE THREAD

**Issue by vlsi** [mikaelgrev/miglayout#70]
Hi,

MigLayout is great. I've implemented a face lifting for Apache JMeter: https://github.com/apache/jmeter/pull/513, and it does make the UI much more solid :)

Here's a question: can I wrap components depending on the width of the window?

For instance, the above link has "action to be taken after a sampler error" group.
The group includes 5 radio buttons. Can I make the buttons wrap to the next line if they don't fit the line?

I tried `new MigLayout("nogrid")`, but it does not really help (which is kind of understandable, but I tried)

**Comment by mikaelgrev** [comment]
Hi Vladimir,

I often want this myself, but unfortunately it's quite hard to add, because ML sets the grid on parsing and it would be hard to change that depending on the size of the container.

Cheers,
Mikael

**Comment by vlsi** [comment]
I see. Thanks for the clarification.
