### ISSUE TITLE
Expose boundsInGrid within CC?

### ISSUE THREAD

**Issue by GregoryHlavac** [mikaelgrev/miglayout#72]
Was working on something kotlin related for an extension set of functions to declare miglayout programmatically with a DSL instead of with raw strings and ran into the problem of CC::boundsInGrid not being exposed with a setter (and having to hack around this with reflection isn't ideal) Any chance this could get a public setter to go along with the getter?

**Comment by mikaelgrev** [comment]
Hello Gregory,

I don´t know why it was package private, but I have pushed a version where it is public just now.

**Comment by GregoryHlavac** [comment]
Thanks. When I get the dsl to an okay state I'll share it somewhere around here too.
