### ISSUE TITLE
set fill on component

### ISSUE THREAD

**Issue by MrKuip** [mikaelgrev/miglayout#79]
I have some layout issues and i'm trying to get my head around 'fill()'.

In the javadoc of for instance CC.grow() I see:
`new ComponentConstraint().noGrid().gap().fill()`

Now there are 2 issues:
1. Object ComponentConstraint() does not exist. I assume that CC() is intended.
2. If CC() is intented CC().fill() does not exist.

Should there be a fill method on CC?

**Comment by mikaelgrev** [comment]
The JavaDoc is wrong. It was called ComponentConstraint in the beginning, but it was shortened to CC.
And components does not have "fill" (only grow and push).

The best place to look for the constraints is probably 
http://www.migcalendar.com/miglayout/mavensite/docs/cheatsheet.html
