### ISSUE TITLE
5.3 release on Maven central before requiring Java 11 ?

### ISSUE THREAD

**Issue by DevCharly** [mikaelgrev/miglayout#83]
Would it be possible to publish a 5.3 version, compiled for Java 8, to Maven central, before switching to Java 11?

Currently using `5.3-SNAPSHOT` because I need PR #76 and Java 8+.
And I'm afraid that the `5.3-SNAPSHOT` will be removed at some point...

Thanks

**Comment by tbee** [comment]
5.3 should be on its way to maven central

**Comment by DevCharly** [comment]
Many thanks 😃
