### ISSUE TITLE
Statement is always true

### ISSUE THREAD

**Issue by dbmalkovsky** [mikaelgrev/miglayout#87]
In `net.miginfocom.layout.Grid` in the Core module starting at line [226](https://github.com/mikaelgrev/miglayout/blob/5c0411925aa4efd8a13cea5c03211c7655646483/core/src/main/java/net/miginfocom/layout/Grid.java#L226) the code is:

<pre>
if (cx >= 0 && cy >= 0) {
	if (cy >= 0) {
		cellXY[0] = cx;
		cellXY[1] = cy;
	} else {    // Only one coordinate is specified. Use the current row (flowx) or column (flowy) to fill in.
		if (lc.isFlowX()) {
			cellXY[0] = cx;
		} else {
			cellXY[1] = cx;
		}
	}
	ensureIndexSizes(cx, cy);
}
</pre>

The `then body` is reached if `cx` **and** `cy` are greater than or equal to zero.   The next test `if (cy >= 0)` has to always be **true**  doesn't it?  Therefore redundant and the `else` is never executed.

**Comment by mikaelgrev** [comment]
You are absolutely correct. Good catch!

**Comment by dbmalkovsky** [comment]
Fixed with this commit: https://github.com/mikaelgrev/miglayout/commit/bba882871a80cdaaa239ecdca146ab41701de5a9
