### ISSUE TITLE
MigPane: AC.constaints should be renamed to AC.constraints (for usage in FXML)

### ISSUE THREAD

**Issue by xzel23** [mikaelgrev/miglayout#92]
I don't know if this is unique to JavaFX, but I think it should be renamed. Maybe "constaints" should be deprecated first and "constraints" added.

**Comment by tbee** [comment]
Good catch! It's in migpane's core. I never saw it.

**Comment by tbee** [comment]
fixed, as suggested

**Comment by tbee** [comment]
11.1-SNAPSHOT
