### ISSUE TITLE
Bug: unable to set logical pixel base to base real pixel

### ISSUE THREAD

**Issue by sylphrena0** [mikaelgrev/miglayout#93]
I have an issue where Java is scaling according to the uiScale and miglayout is doing additional scaling, making components larger than expected on certain devices. When I try to set the logical pixel base, an IllegalArgumentException is thrown.

I am running the following:
```java
PlatformDefaults.setLogicalPixelBase(PlatformDefaults.BASE_REAL_PIXEL);
```

and I get the following exception
```
Exception in thread "main" java.lang.IllegalArgumentException: Unrecognized base: 102
      at net.miginfocom.layout.PlatformDefaults.setLogicalPixelBase(Unknown Source)
      at GUI.Controller.main(Controller.java:258)
```

I am running miglayout 4.3 in Java 17.

**Comment by tbee** [comment]
MigLayout 11.1 does not exist on Maven yet, it it refusing my build without telling why.  Waiting for a resolution by Sonatype. 11.0 is the latest. 

I can't help on the issue

**Comment by DevCharly** [comment]
> I am running miglayout 4.3 ...

This is a very old version.

Try miglayout 11, which should work fine.

If you use maven or gradle, use following coordinates in your build scripts:
`com.miglayout:miglayout-swing:11.0`

Or download it from maven central here:
https://repo1.maven.org/maven2/com/miglayout/miglayout-swing/11.0/
https://repo1.maven.org/maven2/com/miglayout/miglayout-core/11.0/

**Comment by sylphrena0** [comment]
> Try miglayout 11, which should work fine.

Noted! I mentioned in my reply to the issue that I am now on 11.1, and the exception is fixed but the behavior is still not expected. Is there is an alternative method to disable the scaling behavior in miglayout?

**Comment by DevCharly** [comment]
What UI toolkit do you use? Swing, JavaFX or SWT?

For Swing, setting `setLogicalPixelBase(BASE_REAL_PIXEL)` should disable miglayout scaling.
You can check this by setting a breakpoint in method `SwingComponentWrapper.getPixelUnitFactor()` and check the return value.

https://github.com/mikaelgrev/miglayout/blob/657123cb35f45807d46b6140f61d3aa20262e17c/swing/src/main/java/net/miginfocom/swing/SwingComponentWrapper.java#L107-L146

**Comment by sylphrena0** [comment]
I am using swing.

I figured out that this does not appear to be an issue with miglayout, and it's likely my issues were never related. I appreciate your help, I was just setting some borders and sizes without scaling them with my scaling logic.

Thanks for working on this project, it's amazing in comparison to first party layout managers.

**Comment by kl0ck** [comment]
> > I am running miglayout 4.3 ...
> 
> This is a very old version.
> 
> Try miglayout 11, which should work fine.
> 
> If you use maven or gradle, use following coordinates in your build scripts: `com.miglayout:miglayout-swing:11.0`
> 
> Or download it from maven central here: https://repo1.maven.org/maven2/com/miglayout/miglayout-swing/11.0/ https://repo1.maven.org/maven2/com/miglayout/miglayout-core/11.0/

MigLayout 11 does not work for me as my project is using Java 8.

**Comment by tbee** [comment]
Correct, MigLayout 11 requires Java 11. (You really should upgrade your project. 🤷‍♂️)
