### ISSUE TITLE
migcomponents.com is down

### ISSUE THREAD

**Issue by kl0ck** [mikaelgrev/miglayout#99]
> MiG Layout Quick Start Guide v1.2.2
This is a quick start to MiG Layout. For further information look at www.migcomponents.com as it will be
updated with links to the new and relevant information

I was looking for more documentation about this project, and saw www.migcomponents.com on the guide, but that site does not exist anymore.

Is there a changelog of this project? What are the changes between versions? I was testing newer versions on our project  because we use 3.7.4. It seems I can use 4.2 at most, because higher versions break layout.

**Comment by tbee** [comment]
Mig components is AFAIK not derictly related to MigLayout. I figure Mikael intended to write some Swing components as well. https://www.miglayout.com/ is the place to be.

The changes can be found in Github, but besides some bugfixing there aren't many. The Swing project is in maintenance mode, and so is MigLayout. We did upgrade to Java 11 with version 11. 

But what breaks in your layout?

**Comment by kl0ck** [comment]
> The changes can be found in Github, but besides some bugfixing there aren't many. The Swing project is in maintenance mode, and so is MigLayout. We did upgrade to Java 11 with version 11.
> 
> But what breaks in your layout?

I think it is related to issue #53, some kind of scaling maybe.

**Comment by tbee** [comment]
Then I think it may have been fixed. 🤷‍♂️
